### ISSUE TITLE
[feature] 로그인, 페이로그 디자인 수정 & 디버깅

### ISSUE THREAD

**Issue by mututu17** [pknu-wap/WAP-OR#12]
### 👀 Description
로그인, 페이로그 페이지의 바뀐 디자인을 적용하고,
미구현된 디테일한 부분을 고치고 디버깅할 예정입니다.

### 📋 To-do

- [ ] 로그인 페이지 디자인 수정
- [ ] 페이로그 페이지 디자인 수정
- [ ] 페이로그 페이지 반응형 적용
- [ ] 로그인 페이지 연동 준비 (버튼, 클래스 구체화)
- [ ] 페이로그 페이지 연동 준비(버튼, 클래스, 함수 구체화)
- [ ] 디버깅
