### ISSUE TITLE
[feature] 이메일 인증 예외 처리 구현

### ISSUE THREAD

**Issue by pu2rile** [pknu-wap/WAP-OR#21]
### 👀 Description

이메일 인증 예외 처리 기능을 구현합니다.

### 📋 To-do

- [x] 메일 전송 오류(2024.11.08)
- [x] 인증 번호 불일치 오류(2024.11.08)
- [x] 이메일 유효성 오류(2024.11.08)
