### ISSUE TITLE
[feature]페이로그 기능 구현

### ISSUE THREAD

**Issue by dhlee777** [pknu-wap/WAP-OR#27]
### 📋 To-do

- [ ] 예시 (2024.10.10)

- [ ] 페이로그 컨트롤러
- [ ] 페이로그 dto 만들기
- [ ] 페이로그 entity 만들기
- [ ] 페이로그 서비스 만들기
- [ ] 페이로그 레포지터리
