### ISSUE TITLE
[feature] 페이로그 페이지 구현 (UI)

### ISSUE THREAD

**Issue by mututu17** [pknu-wap/WAP-OR#7]
### 👀 Description

페이로그 페이지를 디자인 해보아요.
근데 이제 로그인 페이지와 연결을 곁들인
### 📋 To-do

- [x] 상단바 UI 구현 (2024.10.14)
- [x] 하단바 UI 구현 (2024.10.14)
- [x] 페이로그 페이지를 로그인 페이지와 연결(페이지 이동) (2024.10.14)
- [x] 페이로그 작성 버튼 UI 구현 (2024.10.14)
- [x] 게시물 리스트뷰로 띄우기 (2024.10.15)
- [x] 무한 스크롤 테스트 (2024.10.15)
