### ISSUE TITLE
[feature] 이메일 로그인 구현

### ISSUE THREAD

**Issue by pu2rile** [pknu-wap/WAP-OR#9]
### 👀 Description

이메일 회원가입 및 로그인 기능 구현

### 📋 To-do

- [x] User 엔티티 작성(2024.10.28)
- [x] EmailLoginRequest dto 정의(2024.10.29)
- [x] Usercontroller 로그인 메서드 작성(2024.10.29)
- [x] Userservice에 로그인 로직 구현(2024.10.29)
- [x] UserRepository에 이메일로 사용자 찾기 메서드 작성(2024.10.29)

### 💬 Etc

기능 구현 완료 후 테스트 코드 작성 예정
